### ISSUE TITLE
Indicating areas of documentation open to contributions

### ISSUE THREAD

**Issue by hgcummings** [AutoFixture/AutoFixture.github.io#1]
Are there any areas of this documentation project that are open to contributions? I'd be happy to help writing docs, but don't want to accidentally duplicate effort. If contributions would be useful, would you be willing to raise #good-first-issue tickets for these, so I (or others) could pick them up?

**Comment by zvirja** [comment]
@hgcummings Thank you for your readiness to help with the documentation! It's a big deal :+1:

So far I'm not actively working in this direction, so it's unlikely we could collide. Nevertheless, if you would like to contribute, just fire a WIP PR describing the area/page you working on, so I would not touch it. If you do that from the very beginning, you can be sure that I'm not working on that page myself :wink:
